
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grbtziyqindonbkkkfkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyYnR6aXlxaW5kb25ia2trZmtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NTM3MzEsImV4cCI6MjA1ODMyOTczMX0.RR2d6CrZnblO_wUx3UtnqqCNUoCIe40E4D4jtWSaHZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
